def deleteZerosOP(DataBase, Columns):  # O(1)
    if not isinstance(DataBase, list):  # O(1)
        raise TypeError("The input of the function to remove zeros from the current column is not an array")  # O(1)
    try:  # O(1)
        DBZ = [row for row in DataBase if not all(row[column] == 0 for column in Columns)]  # O(n)
    except TypeError as Error:  # O(1)
        print(Error)  # O(1)
    return DBZ  # O(1)